env:
  browser: true
  jest/globals: true

extends:
  - airbnb
  - plugin:jest/recommended

plugins:
  - jest

rules:
  react/jsx-filename-extension: off
  import/no-extraneous-dependencies:
    - error
    - devDependencies:
        - ./demo/**/*.js
        - webpack.config.js

settings:
  import/resolver:
    babel-module:
