env:
  browser: true
  jest/globals: true

extends:
  - airbnb
  - plugin:jest/recommended

parser: babel-eslint

plugins:
  - babel
  - jest

rules:
  arrow-parens:
    - error
    - as-needed
  react/jsx-filename-extension: off
  react/destructuring-assignment:
    - error
    - never
  import/no-extraneous-dependencies:
    - error
    - devDependencies:
        - ./demo/**/*.js
        - webpack.config.js

settings:
  import/resolver:
    babel-module:
